name: GitHub Actions Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - '**'
      - '!dev'
      - '!main'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for "#deploy" in commit message
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"#deploy"* ]]; then
            echo "Commit contains #deploy, proceeding with build."
          else
            echo "Commit does not contain #deploy, skipping build."
            exit 0
          fi

      - name: Install Vercel CLI
        run: npm install --global vercel@canary

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

  Deploy-Preview:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      # - name: Pull Vercel Environment Information
      #   run: vercel pull --confirm --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: |
          deployment_info=$(vercel deploy --token=${{ secrets.VERCEL_TOKEN }})
          deployment_url=$(echo "$deployment_info")
          echo "deployment_url=${deployment_url}" >> $GITHUB_ENV
          echo "Deployment URL: $deployment_url"

  Comment-PR:
    runs-on: ubuntu-latest
    needs: [Deploy-Preview]
    steps:
      - name: Comment on PR with Deployment URL
        run: |
          comment_body="{\"body\": \"Preview deployment: $deployment_url\"}"
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "@comment.json" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments"

  Cleanup-Preview:
    runs-on: ubuntu-latest
    needs: [Deploy-Preview]
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged
    steps:
      - name: Delete Vercel Preview Deployment
        run: vercel remove $deployment_url --confirm --token=${{ secrets.VERCEL_TOKEN }}